on:
  schedule:
    - cron:  '0 0 * * 0'
  workflow_dispatch:
  push:
    branches:
    - master
name: mapping
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: MALSync
          base: master
          head: master

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
            pip install --upgrade pip
            pip install pillow git+https://github.com/justfoolingaround/animdl.git
      - name: Run generator.py
        run: |
            python "generator.py"
