on:
  schedule:
    - cron:  '0 0 * * 0'
  workflow_dispatch:
  push:
    branches:
    - master
name: mapping
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          github_token: ${secrets.GITHUB_TOKEN}
          base: master
          head: master

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
            pip install --upgrade pip
            pip install tqdm
            pip install pathlib
      - name: Run mapper.py
        run: |
            python "mapper.py"

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Chore: Benchmark Update"
          file_pattern: "api/*"
          repository: .
          skip_fetch: false
